language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0-preview2-006497
services:
  - postgresql
os:  
  - osx
osx_image: xcode7.1  
before_script:
  - psql -c 'create database migrations;' -U postgres
  - psql -c 'create schema "Moo" AUTHORIZATION postgres;' -U postgres
script:  
  - sh ./build.sh